# Hello python!

In [5]:
x = 3
print type(x)
x += 2.3 
print type(x)
x -= 1 
print x
x,y = 99.99,5 
print x,y

<type 'int'>
<type 'float'>
4.3
99.99 5


# Python introduction : append 

In [11]:
my_list = []
my_list.append(1) 
my_list.append(2) 
my_list2 = [55.55,"Hi",3,99,222,222]
my_list2[0]=333.333

print len(my_list),sum(my_list),my_list2.count(222)
print my_list2[0],my_list2[-1],my_list2[1:3],my_list2[2:]

2 3 2
333.333 222 ['Hi', 3] [3, 99, 222, 222]


# Python introduction : dictionary

In [6]:
passwd={'Mars':00000,'Mark':56680}
passwd['Happy']=9999    
passwd['Smile']=123456

print passwd['Mark']

print passwd
print passwd.keys()
print passwd.values()
print passwd.get('Tony')

56680
{'Happy': 9999, 'Smile': 123456, 'Mark': 56680, 'Mars': 0}
['Happy', 'Smile', 'Mark', 'Mars']
[9999, 123456, 56680, 0]
None


# Python introduction : for loop

In [5]:
my_list=[]
for i in range(0,10):  #"""//for(i=0;i<10;i++)"""
    my_list.append(i+1)

for i in my_list: #"""//for(i=0;i<my_list.length();i++)"""
    print i #"""//cout<<my_list[i]"""

if my_list[0]==1 and len(my_list)<10:
    my_list[0]+=1
    print "1 state"

elif (11 in my_list) or (len(my_list)==1):
    print "2 state"
    print "range(i,j) is i~j-1"

else:
    print "3 state"  
    print "none of above"

1
2
3
4
5
6
7
8
9
10
3 state
none of above


# Python introduction : function

In [7]:
def my_function(x,y):
    return x-10,y+10

if __name__ == '__main__':

    x,y = my_function(10,20)
    print x,y

0 30


# Python introduction : numpy

In [9]:
# encoding: utf-8
# numpy模組 - 基本用法:創建矩陣
import numpy as np

# 建立一個 np array
arr = np.array([[1,2,3],[4,5,6]])    #放入list就會轉換喔!
print "建立一個 np array"
print arr 
print arr.shape
#印出 [[1,2,3],[4,5,6]]的 2*3 矩陣

# 建立一個 全為 0 的 2*3 矩陣，並指定為 int16格式
zero_arr = np.zeros((2,3), dtype=np.int16)
print "建立一個 全為 0 的 2*3 矩陣，並指定為 int16格式"
print zero_arr
print zero_arr.shape[0]
#印出 [[0,0,0],[0,0,0]] 的 2*3 矩陣

# 建立一個長度為12、數值從0~11、格式為 int64 的一維陣列
onedim_arr = np.arange(12, dtype=np.int64)
print "建立一個長度為12、數值從0~11、格式為 int64 的一維陣列"
print onedim_arr
print onedim_arr.shape[0]
#印出 [0,1,2,3,4,5,6,7,8,9,10,11]

# 建立一個數值從0~11、格式為int64，但是是 3*4 的矩陣
reshape_arr = np.arange(12, dtype=np.int64).reshape( (3,4) )
print "建立一個數值從0~11、格式為int64，但是是 3*4 的矩陣"
print reshape_arr
#印出 [ [0,1,2,3],[4,5,6,7],[8,9,10,11] ] 的 3*4矩陣

# 建立一個最小值1，最大值50，共分五塊相等間距的矩陣
slice_arr = np.linspace(1,50,5)
print "建立一個最小值1，最大值50，共分五塊相等間距的矩陣"
print slice_arr
#印出 [  1.    13.25  25.5   37.75  50.  ] 的 1*5 矩陣
#要轉成 5*1 的矩陣就在後面加上 .reshape((5*1)) 就可以喔！

# 建立一個隨機在0~1之間分布的 4*2 矩陣
random_arr = np.random.random( (4, 2) )
print "建立一個隨機在0~1之間分布的 4*2 矩陣"
print random_arr
#印出 [[ 0.92615029  0.12676952], [ 0.33146324  0.51952945],
#[ 0.37010443  0.23092601], [ 0.11052635  0.78243148]]
#值是隨機的，所以你印出來一定跟我不一樣喔！

建立一個 np array
[[1 2 3]
 [4 5 6]]
(2, 3)
建立一個 全為 0 的 2*3 矩陣，並指定為 int16格式
[[0 0 0]
 [0 0 0]]
2
建立一個長度為12、數值從0~11、格式為 int64 的一維陣列
[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
建立一個數值從0~11、格式為int64，但是是 3*4 的矩陣
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
建立一個最小值1，最大值50，共分五塊相等間距的矩陣
[  1.    13.25  25.5   37.75  50.  ]
建立一個隨機在0~1之間分布的 4*2 矩陣
[[ 0.90595878  0.25140201]
 [ 0.89271876  0.82805826]
 [ 0.42571683  0.04432017]
 [ 0.20722022  0.8555153 ]]
